# Site settings
title: Crypto Asset Lab
email:
description: Research initiative on bitcoin and crypto assets as investment opportunity, fintech innovation, and regulatory challenge.
#baseurl: "" # the subpath of your site, e.g. /blog/
baseurl: ""
url: ""

include:
  - .htaccess
  - _pages
  - _posts

sass:
  sass_dir: _sass

# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus:

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics:

# Build settings
markdown: kramdown
excerpt_separator: "\n\n"

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  parse_block_html: true # default for kramdown is false. This will enable using Markdown links

# Use the following plug-ins
plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
