# Site settings
title: Crypto Asset Lab
email:
description: # this means to ignore newlines until "baseurl:"
#baseurl: "" # the subpath of your site, e.g. /blog/
url: http://cryptoassetlab.diseade.unimib.it/
logo:

# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus:

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics:

# Build settings
markdown: kramdown

# Use the following plug-ins
plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

theme: jekyll-theme-slate